# Generated by Django 2.1 on 2019-05-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=100, unique=True)),
                ('filing', models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, verbose_name='是否备案')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='采购时间')),
                ('expire_time', models.DateField(blank=True, null=True, verbose_name='到期时间')),
                ('is_encryption', models.BooleanField(choices=[(True, '是'), (False, '否')], default=True, verbose_name='是否HTTPS')),
                ('ssl_begin', models.DateField(blank=True, null=True, verbose_name='SSL到期时间')),
                ('ssl_expire', models.DateField(blank=True, null=True, verbose_name='SSL 到期时间')),
                ('ssl_issuer', models.CharField(blank=True, max_length=64, null=True, verbose_name='SSL证书品牌')),
                ('remainder_days', models.IntegerField(help_text='证书剩余天数', null=True)),
                ('is_active', models.BooleanField(choices=[(True, '是'), (False, '否')], default=True, verbose_name='状态')),
                ('vendor', models.CharField(blank=True, max_length=64, null=True, verbose_name='厂商')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('comment', models.TextField(blank=True, default='', max_length=128, null=True, verbose_name='Comment')),
                ('platform', models.ForeignKey(on_delete=False, related_name='platformS', to='assets.Platform', verbose_name='项目')),
                ('resolve', models.ForeignKey(help_text='域名解析地址', null=True, on_delete=False, related_name='resolveS', to='assets.Assets')),
            ],
        ),
    ]
