# Generated by Django 2.1 on 2019-05-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='env',
            field=models.CharField(choices=[('DEV', '开发环境'), ('TK', '测试环境'), ('PRE', '预发布环境'), ('Online', '线上环境')], default='', help_text='项目名称，DEV，TK', max_length=10, verbose_name='环境'),
        ),
    ]
