# Generated by Django 2.1 on 2019-05-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190527_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='env',
            field=models.CharField(choices=[('DEV', '开发环境'), ('TK', '测试环境'), ('PRE', '预发布环境'), ('Online', '线上环境')], default='', max_length=10, verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='application',
            name='items',
            field=models.CharField(max_length=100, verbose_name='应用'),
        ),
        migrations.AlterField(
            model_name='application',
            name='package_name',
            field=models.CharField(default='', max_length=100, verbose_name='包名'),
        ),
        migrations.AlterField(
            model_name='application',
            name='platform',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='assets.Platform', verbose_name='平台代码'),
        ),
    ]
